repo_name: 'WFZ7789/Luogu_wfirstzhang'
repo_url: 'https://github.com/WFZ7789/Luogu_wfirstzhang'

site_name: WFZ-7789
site_description: 你猜
site_author: wfirstzhang
site_url: wfz.pages.dev
strict: false

copyright: 'WFLengXueNong and Her Students'
